"""create credit cards and statements

Revision ID: e7ae64bddf45
Revises: 4fd2d7e95ffb
Create Date: 2026-07-17 20:43:15.333012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ae64bddf45'
down_revision: Union[str, Sequence[str], None] = '4fd2d7e95ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_cards_payment_account_id'), 'credit_cards', ['payment_account_id'], unique=False)
    op.create_index(op.f('ix_credit_cards_user_id'), 'credit_cards', ['user_id'], unique=False)
    op.create_table('billing_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_statements_credit_card_id'), 'billing_statements', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_billing_statements_due_on'), 'billing_statements', ['due_on'], unique=False)
    op.create_index(op.f('ix_billing_statements_user_id'), 'billing_statements', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('credit_card_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('statement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'credit_cards', ['credit_card_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'billing_statements', ['statement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'statement_id')
    op.drop_column('transactions', 'credit_card_id')
    op.drop_index(op.f('ix_billing_statements_user_id'), table_name='billing_statements')
    op.drop_index(op.f('ix_billing_statements_due_on'), table_name='billing_statements')
    op.drop_index(op.f('ix_billing_statements_credit_card_id'), table_name='billing_statements')
    op.drop_table('billing_statements')
    op.drop_index(op.f('ix_credit_cards_user_id'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_payment_account_id'), table_name='credit_cards')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
